name: MRT Monitor

on:
  schedule:
    # This runs every 5 minutes from 5:00 AM to 1:00 AM Singapore Time
    # UTC 21:00 (Previous Day) to UTC 17:00 (Current Day)
    - cron: '*/5 21-23 * * *'  # 5:00 AM - 7:59 AM SGT
    - cron: '*/5 0-16 * * *'   # 8:00 AM - 12:59 AM SGT
  workflow_dispatch:          # Keeps the manual "Play" button active

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python mrt_bot.py
